#!/usr/bin/env python

import pdb
import sys
import time
import argparse
import logging

from opus20 import Opus20, OPUS20_CHANNEL_SPEC, PickleStore

clock = time.perf_counter
logger = logging.getLogger('opus_cli')

def extended_int(string):
    if string.startswith('0x'):
        return int(string, 16)
    else:
        return int(string)

def main():

    parser = argparse.ArgumentParser(description="CLI for the Lufft Opus20")
    parser.add_argument('host', help='hostname of the device')
    parser.add_argument('--port', '-p', type=int, help='port for TCP connections')
    parser.add_argument('--timeout', '-t', type=float, help='timeout for the TCP connection')
    parser.add_argument('--loglevel', '-l', choices=['CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG'], help='log level')
    subparsers = parser.add_subparsers(help='cmd help', dest='cmd')
    parser_a = subparsers.add_parser('list', help='list all possible channels')
    parser_b = subparsers.add_parser('get', help='get the value(s) of specific channel(s)')
    parser_b.add_argument('channel', type=extended_int, nargs='+', help='The selected channel(s)')
    parser_c = subparsers.add_parser('download', help='download the logs')
    parser_c.add_argument('persistance_file', help='file to store the logs in')
    args = parser.parse_args()

    if not args.cmd: parser.error('please select a command')

    if args.loglevel:
        logging.basicConfig(level=getattr(logging, args.loglevel.upper()))

    start = clock()
    try:
        kwargs = {}
        if args.port: kwargs['port'] = args.port
        if args.timeout: kwargs['timeout'] = args.timeout
        o20 = Opus20(args.host, **kwargs)

        if args.cmd == 'list':
            for channel in o20.available_channels:
                print("Channel {:5d} (0x{:04X}): {name:22s}  unit: {unit:6s} offset: {offset}".format(channel, channel, **OPUS20_CHANNEL_SPEC[channel]))
        if args.cmd == 'get':
            if len(args.channel) > 1:
                for channel in o20.multi_channel_value(args.channel):
                    print("{:.3f}".format(channel))
            else:
                print("{:.3f}".format(o20.channel_value(args.channel[0])))
        if args.cmd == 'download':
            ps = PickleStore(args.persistance_file)
            try:
                max_ts = ps.max_ts()[o20.device_id]
            except KeyError:
                max_ts = None
            log_data = o20.download_logs(start_datetime=max_ts)
            ps.add_data(o20.device_id, log_data)
            ps.persist()

    except ConnectionRefusedError as e:
        parser.error("Could not connect to host {}: {}".format(args.host, e))

    finally:
        o20.disconnect()
    end = clock()
    logger.info("script running time (net): {:.6f} seconds.".format(end-start))


if __name__ == "__main__": main()
